spring:
  application:
    name: evenly

  # 스프링 관련 로그 색상 활성화
  output:
    ansi:
      enabled: ALWAYS

  # JPA 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  # 추후 SQL 사용 시 수정
    show-sql: true
    # JPA(Hibernate)에서 SQL 로그 남길 때 보안, 성능 이슈로 출력되지 않는데 이걸 보이기 위함
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder:
                log: true

  # 데이터베이스 설정
  datasource:
    url:
    username:
    password:
    driver-class-name:

  #Redis
  redis:
    host: localhost
    port: 6379
    password:


jwt:
  secret:   # ✅ AccessToken 서명 키 (Base64)
  refresh_secret:   # ✅ RefreshToken 서명 키 (Base64)
  expiration_time: 30  # AccessToken 만료 시간 (분)

server:
  port: 8080
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never